export const OCP_RUNTIME_MARKER = "generated by ocp setup"

export {
  detectHostId,
  hostCacheDir,
  installPathBridge,
  toolRolesForHostId,
} from "./runtime-host"

export {
  usageIntegrationForHost,
  installUsageReconciliation,
  recordFinishUsage,
} from "./usage-reconciliation"

export {
  adaptLanguageModel,
  adoptStreamPart,
  canonicalToolKey,
  defaultBashDescription,
  normalizeToolInputForSchema,
  policyForHostId,
  policyFromProfile,
  wrapProviderModule,
  wrapProviderModuleForProfile,
  wrapProviderSdk,
  wrapProviderSdkForProfile,
} from "./language-model"

export {
  buildVocabulary,
  diffTodos,
  fanoutId,
  originalCallId,
  reconstructHostTodos,
  translateCall,
  translateCatalog,
  translatePrompt,
} from "./vocabulary"
