/**
 * Generate install-tree provider shims (Option B).
 *
 * Strategy: in-place entry interception. Hosts (incl. MiMo) often load custom
 * providers via a direct `file://…/dist/index.js` URL from the classic plugin
 * (`MODULE_URL`), which bypasses package.json `exports`. So `ocp setup`:
 * 1. renames the package entry to `*.ocp-original.js` (install cache only)
 * 2. writes the shim at the original entry path
 * 3. drops an inlined `ocp-lm-runtime.js` and `ocp-shim-meta.json` beside the entry
 *
 * Upstream plugin repos / published tarballs are never edited — only the host
 * install tree after reify. Re-run setup after plugin install/upgrade.
 */

import { readFileSync } from "node:fs"

export const SHIM_FILENAME = "ocp-provider-shim.js"
export const RUNTIME_FILENAME = "ocp-lm-runtime.js"
export const SHIM_META_FILENAME = "ocp-shim-meta.json"
export const OCP_ORIGINAL_EXPORTS_KEY = "ocpOriginalExports"
export const ORIGINAL_SUFFIX = ".ocp-original.js"
export const SHIM_MARKER = "generated by ocp setup"

export type ShimMeta = {
  /** Relative path from package root to the backed-up original entry. */
  original: string
  /** Relative path from package root to the live entry (shim location). */
  entry: string
  /** Export names discovered at setup time (excluding default). */
  exportNames: string[]
  /** Setup-time host hint; runtime still re-detects. */
  hostHint?: string
  /** Always inplace-entry for file:// compatibility. */
  strategy: "inplace-entry"
}

/** Zero-dep runtime source copied into each shimmed provider package. */
export function providerShimRuntimeSource(): string {
  const runtimeUrl = new URL(`../dist/${RUNTIME_FILENAME}`, import.meta.url)

  try {
    return readFileSync(runtimeUrl, "utf8")
  } catch (err) {
    throw new Error(
      `Missing ${RUNTIME_FILENAME}. Run bun run build before ocp setup.`,
      { cause: err },
    )
  }
}

/** Backup path beside an entry file: `index.js` → `index.ocp-original.js`. */
export function originalBackupPath(entryPath: string): string {
  if (entryPath.endsWith(".js")) return `${entryPath.slice(0, -3)}${ORIGINAL_SUFFIX}`
  if (entryPath.endsWith(".mjs")) return `${entryPath.slice(0, -4)}${ORIGINAL_SUFFIX}`
  return `${entryPath}${ORIGINAL_SUFFIX}`
}

/**
 * Render the ESM shim that sits at the package entry path.
 * `meta.original` / runtime are imported as siblings of the shim file.
 */
export function renderProviderShimSource(meta: ShimMeta): string {
  const original = JSON.stringify(meta.original)
  const hostHint = JSON.stringify(meta.hostHint ?? "")
  const exportLines = meta.exportNames
    .filter((name) => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name))
    .map((name) => `export const ${name} = __wrapped[${JSON.stringify(name)}]`)
    .join("\n")

  return `/* ${SHIM_MARKER} — wraps create* → languageModel for host adoption; original entry untouched beside this file */
import {
  detectHostId,
  installPathBridge,
  policyForHostId,
  toolRolesForHostId,
  wrapProviderModule,
} from "./${RUNTIME_FILENAME}"

const __host = detectHostId(process.env, process.argv, process.execPath, ${hostHint})
installPathBridge(__host, process.env)
const __original = await import(${original})
const __policy = policyForHostId(__host)
const __roles = toolRolesForHostId(__host)
const __wrapped = wrapProviderModule(__original, __policy, __roles)

export default __wrapped.default
${exportLines ? `${exportLines}\n` : ""}`
}

export function renderShimMeta(meta: ShimMeta): string {
  return `${JSON.stringify(meta, null, 2)}\n`
}

/** Relative import path from one file to another (both POSIX-ish relative). */
export function relativeImportPath(fromFile: string, toFile: string): string {
  const fromParts = fromFile.replace(/\\/g, "/").split("/")
  const toParts = toFile.replace(/\\/g, "/").split("/")
  fromParts.pop()
  while (
    fromParts.length > 0 &&
    toParts.length > 0 &&
    fromParts[0] === toParts[0]
  ) {
    fromParts.shift()
    toParts.shift()
  }
  const rel = `${"../".repeat(fromParts.length)}${toParts.join("/")}`
  return rel.startsWith(".") ? rel : `./${rel}`
}
