/**
 * Generate install-tree provider shims (Option B).
 *
 * Strategy: in-place entry instrumentation. Hosts (incl. MiMo) often load custom
 * providers via a direct `file://…/dist/index.js` URL from the classic plugin
 * (`MODULE_URL`), which bypasses package.json `exports`. So `ocp setup`:
 * 1. preserves the stock module body at its original path
 * 2. instruments exported create* bindings with the host adoption wrapper
 * 3. drops `ocp-lm-runtime.js` and `ocp-shim-meta.json` beside the entry
 *
 * There is deliberately no backup file. Reinstall/rebuild is the source of
 * truth for reverting to the out-of-box package; setup always regenerates the
 * instrumented entry from the stock body currently at that path.
 */

import { readFileSync } from "node:fs"

export const RUNTIME_FILENAME = "ocp-lm-runtime.js"
export const SHIM_META_FILENAME = "ocp-shim-meta.json"
export const SHIM_MARKER = "generated by ocp setup"

const HEADER_START = `/* ${SHIM_MARKER}: instrumented entry header */`
const HEADER_END = `/* ${SHIM_MARKER}: end instrumented entry header */`
const BINDINGS_START = `/* ${SHIM_MARKER}: instrumented factory bindings */`
const BINDINGS_END = `/* ${SHIM_MARKER}: end instrumented factory bindings */`
const MUTABLE_CONST_PREFIX = `${SHIM_MARKER}: mutable const `

export type ShimFactoryBinding = {
  exportName: string
  localName: string
  declaration: "function" | "const" | "let" | "var" | "class"
}

export type ShimMeta = {
  /** Relative path from package root to the instrumented entry. */
  entry: string
  /** Export/local bindings wrapped in-place. */
  factories: ShimFactoryBinding[]
  /** Setup-time host hint; runtime still re-detects. */
  hostHint?: string
  /** Always instrumented-entry for direct file:// compatibility. */
  strategy: "instrumented-entry"
}

/** Zero-dep runtime source copied into each shimmed provider package. */
export function providerShimRuntimeSource(): string {
  const runtimeUrl = new URL(`../dist/${RUNTIME_FILENAME}`, import.meta.url)

  try {
    return readFileSync(runtimeUrl, "utf8")
  } catch (err) {
    throw new Error(
      `Missing ${RUNTIME_FILENAME}. Run bun run build before ocp setup.`,
      { cause: err },
    )
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

/** Remove OCP instrumentation while preserving the package's module body. */
export function stripProviderShimSource(source: string): string {
  const headerPattern = new RegExp(
    `${escapeRegExp(HEADER_START)}[\\s\\S]*?${escapeRegExp(HEADER_END)}\\n?`,
  )
  const bindingsPattern = new RegExp(
    `\\n?${escapeRegExp(BINDINGS_START)}[\\s\\S]*?${escapeRegExp(BINDINGS_END)}\\n?`,
  )
  return source
    .replace(headerPattern, "")
    .replace(bindingsPattern, "")
    .replace(
      new RegExp(
        `/\\* ${escapeRegExp(MUTABLE_CONST_PREFIX)}([A-Za-z_$][A-Za-z0-9_$]*) \\*/ let(\\s+)([A-Za-z_$][A-Za-z0-9_$]*)`,
        "g",
      ),
      (match, markedName: string, whitespace: string, declaredName: string) =>
        markedName === declaredName
          ? `const${whitespace}${declaredName}`
          : match,
    )
}

function makeFactoryConstsMutable(
  source: string,
  factories: readonly ShimFactoryBinding[],
): string {
  let result = source
  for (const factory of factories) {
    if (factory.declaration !== "const") continue
    const name = escapeRegExp(factory.localName)
    const pattern = new RegExp(`\\b(export\\s+)?const(\\s+${name}\\b)`)
    result = result.replace(
      pattern,
      (_match, exported = "", rest: string) =>
        `${exported}/* ${MUTABLE_CONST_PREFIX}${factory.localName} */ let${rest}`,
    )
  }
  return result
}

/** Instrument a stock ESM entry without copying it to a backup file. */
export function renderProviderShimSource(
  meta: ShimMeta,
  source: string,
): string {
  const hostHint = JSON.stringify(meta.hostHint ?? "")
  const stockSource = stripProviderShimSource(source)
  const instrumentedSource = makeFactoryConstsMutable(stockSource, meta.factories)
  const factoryEntries = meta.factories
    .map(
      ({ exportName, localName }) =>
        `  ${JSON.stringify(exportName)}: ${localName},`,
    )
    .join("\n")
  const assignments = meta.factories
    .filter(
      (factory, index, factories) =>
        factories.findIndex((item) => item.localName === factory.localName) === index,
    )
    .map(
      ({ exportName, localName }) =>
        `${localName} = __ocpWrappedFactories[${JSON.stringify(exportName)}]`,
    )
    .join("\n")

  const header = `${HEADER_START}
import {
  detectHostId,
  installPathBridge,
  policyForHostId,
  toolRolesForHostId,
  wrapProviderModule,
} from "./${RUNTIME_FILENAME}"

const __host = detectHostId(process.env, process.argv, process.execPath, ${hostHint})
installPathBridge(__host, process.env)
const __policy = policyForHostId(__host)
const __roles = toolRolesForHostId(__host)
${HEADER_END}`

  const bindings = `${BINDINGS_START}
const __ocpWrappedFactories = wrapProviderModule({
${factoryEntries}
}, __policy, __roles)
${assignments}
${BINDINGS_END}`

  return `${header}\n${instrumentedSource}\n${bindings}\n`
}

export function renderShimMeta(meta: ShimMeta): string {
  return `${JSON.stringify(meta, null, 2)}\n`
}
