#!/usr/bin/env bash
# Restore a consumer plugin checkout after local OCP testing.
#
# The local-dev scripts intentionally install compatibility facades, replace
# provider package entries with OCP shims, and may point a host cache/config at
# an absolute checkout. This command removes only that test state and rebuilds
# the provider against the dependencies declared by its own lockfile.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/host-dev-common.sh
source "$ROOT/scripts/host-dev-common.sh"

clean_test_die() {
  echo "clean-test-state: $*" >&2
  exit 1
}

usage() {
  cat <<EOF
Usage: ${0##*/} [--provider PATH] [--host mimo|kilo] [--packages-dir PATH]

Restore a provider checkout to stock test state. By default this only cleans
the provider checkout. With --host, also remove the selected provider's host
cache entries, recognizable OCP install-tree overrides, and local config
references.

Options:
  --provider PATH       Consumer plugin checkout (default: sibling or ~/Projects)
  --host HOST           Also clean MiMo or Kilo cache/config state
  --packages-dir PATH   Override the host packages directory (requires --host)
  -h, --help            Show this help

Environment:
  OCP_DEV_PROVIDER_PATH  Default provider checkout
  OCP_DEV_PLUGIN         Provider package name (default: cursor-opencode-provider)
  MIMOCODE_HOME / KILO_CONFIG_DIR / XDG_*  Host path overrides

The provider checkout is rebuilt after dependency reinstallation. This is
deliberately not a backup restore: provider source plus its lockfile are the
source of truth, and existing host config values overwritten by an older test
run cannot be reconstructed when no backup exists.
EOF
}

provider_path=""
host=""
packages_dir=""

while (($#)); do
  case "$1" in
    --provider)
      (($# >= 2)) || clean_test_die "--provider requires a path"
      provider_path="$2"
      shift 2
      ;;
    --host)
      (($# >= 2)) || clean_test_die "--host requires mimo or kilo"
      host="$2"
      shift 2
      ;;
    --packages-dir)
      (($# >= 2)) || clean_test_die "--packages-dir requires a path"
      packages_dir="$2"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      clean_test_die "unknown argument: $1 (use --help)"
      ;;
  esac
done

[[ -z "$packages_dir" || -n "$host" ]] || clean_test_die "--packages-dir requires --host"
if [[ -n "$host" && "$host" != "mimo" && "$host" != "kilo" ]]; then
  clean_test_die "unknown host: $host (expected mimo or kilo)"
fi

if [[ -z "$provider_path" ]]; then
  provider_path="$(host_dev_default_provider_path "$ROOT")"
fi
provider_path="$(cd "$provider_path" && pwd)"
host_dev_assert_safe_provider_checkout "$provider_path"

echo "clean-test-state: removing provider dependencies from ${provider_path}"
host_dev_remove_provider_dependencies "$provider_path"
echo "clean-test-state: reinstalling provider dependencies from its lockfile"
host_dev_reinstall_provider_dependencies "$provider_path"
echo "clean-test-state: rebuilding stock provider output"
host_dev_refresh_provider_stock "$provider_path"

plugin="${OCP_DEV_PLUGIN:-cursor-opencode-provider}"

verify_provider_stock() {
  local dist="${provider_path}/dist"
  local entry="${dist}/index.js"
  local plugin_pkg="${provider_path}/node_modules/@opencode-ai/plugin"
  local sdk_pkg="${provider_path}/node_modules/@opencode-ai/sdk"

  [[ -d "$plugin_pkg" && ! -L "$plugin_pkg" ]] ||
    clean_test_die "@opencode-ai/plugin is still not a real installed package"
  [[ -d "$sdk_pkg" && ! -L "$sdk_pkg" ]] ||
    clean_test_die "@opencode-ai/sdk is still not a real installed package"
  grep -q '"name": "@opencode-ai/plugin"' "$plugin_pkg/package.json" ||
    clean_test_die "installed plugin package is not @opencode-ai/plugin"
  grep -q '"name": "@opencode-ai/sdk"' "$sdk_pkg/package.json" ||
    clean_test_die "installed SDK package is not @opencode-ai/sdk"
  if grep -q 'generated by ocp setup' "$entry"; then
    clean_test_die "provider entry still contains an OCP shim marker"
  fi
  for artifact in index.ocp-original.js ocp-lm-runtime.js ocp-shim-meta.json; do
    [[ ! -e "${dist}/${artifact}" ]] ||
      clean_test_die "generated OCP artifact remains: ${dist}/${artifact}"
  done
  echo "clean-test-state: provider checkout is stock"
}

verify_provider_stock

if [[ -n "$host" ]]; then
  if [[ -z "$packages_dir" ]]; then
    packages_dir="$(host_dev_cache_packages_dir "$host")"
  fi
  packages_dir="$(cd "$packages_dir" 2>/dev/null && pwd || true)"
  [[ -n "$packages_dir" ]] || clean_test_die "host packages directory does not exist"

  echo "clean-test-state: removing cached ${plugin} installs from ${packages_dir}"
  host_dev_clean_plugin_installs "$packages_dir" "$plugin"

  echo "clean-test-state: removing recognizable OCP install-tree overrides"
  bun - "$packages_dir" "$ROOT" <<'BUN'
import { existsSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const [packagesDir, ocpRoot] = process.argv.slice(2)
const facadePlugin = resolve(ocpRoot, "packages/facade-plugin")
const facadeSdk = resolve(ocpRoot, "packages/facade-sdk")

function isFacadeValue(value, facadeRoot) {
  if (typeof value !== "string") return false
  return value.includes("@opencode-compat/facade-") ||
    value === `file:${facadeRoot}` ||
    value === facadeRoot
}

function isGeneratedRoot(data) {
  return data?.name === "opencode-compat-overrides" && data?.private === true
}

const paths = [join(packagesDir, "package.json")]
if (existsSync(packagesDir)) {
  for (const entry of readdirSync(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === "node_modules" || entry.name.startsWith(".")) continue
    paths.push(join(packagesDir, entry.name, "package.json"))
  }
}

for (const path of paths) {
  if (!existsSync(path)) continue
  let data
  try {
    data = JSON.parse(readFileSync(path, "utf8"))
  } catch {
    continue
  }
  const overrides = data?.overrides
  if (!overrides || typeof overrides !== "object" || Array.isArray(overrides)) continue

  let changed = false
  if (isFacadeValue(overrides["@opencode-ai/plugin"], facadePlugin)) {
    delete overrides["@opencode-ai/plugin"]
    changed = true
  }
  if (isFacadeValue(overrides["@opencode-ai/sdk"], facadeSdk)) {
    delete overrides["@opencode-ai/sdk"]
    changed = true
  }
  if (!changed) continue

  if (Object.keys(overrides).length === 0) delete data.overrides
  const remaining = Object.keys(data)
  if (isGeneratedRoot(data) && remaining.every((key) => key === "name" || key === "private")) {
    unlinkSync(path)
    console.log(`clean-test-state: removed generated override file ${path}`)
  } else {
    writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`, "utf8")
    console.log(`clean-test-state: removed OCP overrides from ${path}`)
  }
}
BUN

  config_file="$(host_dev_config_file "$host")"
  echo "clean-test-state: removing local ${plugin} references from ${config_file}"
  bun - "$config_file" "$provider_path" "$host" <<'BUN'
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

const [configPath, providerPath, host] = process.argv.slice(2)
if (!existsSync(configPath)) process.exit(0)

const provider = resolve(providerPath)
const entry = join(provider, "dist/index.js")
const localSpecs = new Set([provider, entry, `file://${entry}`])
const stripComments = (source) => source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/.*$/gm, "$1")

let data
try {
  data = JSON.parse(stripComments(readFileSync(configPath, "utf8")))
} catch {
  console.error(`clean-test-state: could not parse ${configPath}; left it untouched`)
  process.exit(0)
}

let changed = false
if (Array.isArray(data.plugin)) {
  const next = data.plugin.filter((value) => typeof value !== "string" || !localSpecs.has(value))
  if (next.length !== data.plugin.length) changed = true
  if (next.length === 0) delete data.plugin
  else data.plugin = next
}

const cursor = data.provider?.cursor
if (cursor && typeof cursor === "object" && localSpecs.has(cursor.npm)) {
  delete data.provider.cursor
  if (Object.keys(data.provider).length === 0) delete data.provider
  changed = true
}

if (changed) {
  writeFileSync(configPath, `${JSON.stringify(data, null, 2)}\n`, "utf8")
  console.log(`clean-test-state: removed local provider references from ${configPath}`)
}

if (host === "kilo") {
  for (const name of ["opencode.json", "opencode.jsonc", "config.json"]) {
    const candidate = join(dirname(configPath), name)
    if (candidate === configPath || !existsSync(candidate)) continue
    try {
      const alternate = JSON.parse(stripComments(readFileSync(candidate, "utf8")))
      const keys = Object.keys(alternate)
      if (keys.length === 1 && keys[0] === "plugin" && Array.isArray(alternate.plugin) &&
          alternate.plugin.length === 1 && localSpecs.has(alternate.plugin[0])) {
        unlinkSync(candidate)
        console.log(`clean-test-state: removed generated config ${candidate}`)
      }
    } catch {
      // Preserve malformed or user-owned alternate configs.
    }
  }
}
BUN
fi

echo "clean-test-state: clean testing state restored"
