#!/usr/bin/env bash
# Inspect and unwind local OCP host wiring.
#
#   ocp-dev.sh status                 what is wired on this machine right now
#   ocp-dev.sh revert <host>          undo exactly one host
#   ocp-dev.sh revert --all           undo every wired host
#   ocp-dev.sh repair-stock           restore a provider checkout dirtied by
#                                     the older in-place host-dev scripts
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/ocp-dev-common.sh
source "${script_dir}/ocp-dev-common.sh"

ocp_dev_repo_root() {
  echo "${OCP_DEV_ROOT:-$(cd "${script_dir}/.." && pwd)}"
}

ocp_dev_default_provider_path() {
  local root sibling
  root="$(ocp_dev_repo_root)"
  if [[ -n "${OCP_DEV_PROVIDER_PATH:-}" && -f "${OCP_DEV_PROVIDER_PATH}/package.json" ]]; then
    (cd "${OCP_DEV_PROVIDER_PATH}" && pwd)
    return 0
  fi
  sibling="$(cd "${root}/.." && pwd)/cursor-opencode-provider"
  if [[ -f "${sibling}/package.json" ]]; then
    echo "$sibling"
    return 0
  fi
  ocp_dev_die "provider checkout not found; set OCP_DEV_PROVIDER_PATH"
}

status_one() {
  local host="$1"
  local manifest
  manifest="$(ocp_dev_manifest_path "$host")"

  if [[ ! -f "$manifest" ]]; then
    case "$host" in
      pi | omp)
        # Pi-family wiring goes through the host's own package manager
        # (`pi install` / `omp plugin install`), which this manifest does not
        # track yet. Say so rather than implying the host is unwired.
        printf '  %-6s no OCP dev manifest (pi-family wiring is not tracked here — use `%s` tooling)\n' \
          "$host" "$host"
        ;;
      *) printf '  %-6s not wired\n' "$host" ;;
    esac
    return 0
  fi

  ocp_dev_require_bun
  bun - "$manifest" "$host" <<'BUN'
import { readFileSync, existsSync } from "node:fs"

const [manifestPath, host] = process.argv.slice(2)
const m = JSON.parse(readFileSync(manifestPath, "utf8"))
const entry = m.config?.pluginAdded
const live = entry ? existsSync(entry) : false

// Report the facade/provider source so a local-vs-npm swap is visible rather
// than surprising: they run different code on both axes.
const source = m.mode === "local" ? (m.wrapperDir ?? "?") : "npm registry"
console.log(`  ${host.padEnd(6)} wired (${m.mode})`)
console.log(`         entry:   ${entry ?? "?"}${live ? "" : "   [MISSING]"}`)
console.log(`         source:  ${source}`)
console.log(`         config:  ${m.config?.path ?? "?"}`)
console.log(`         ocp:     ${m.ocpVersion ?? "?"}   updated ${m.updated ?? "?"}`)
BUN
}

cmd_status() {
  local provider host
  echo "OCP local dev status"
  echo "  state dir: $(ocp_dev_state_root)"
  echo ""

  echo "Hosts:"
  for host in $(ocp_dev_known_hosts); do
    status_one "$host"
  done
  echo ""

  provider="$(ocp_dev_default_provider_path)" || return 1
  echo "Stock provider checkout: ${provider}"
  local entry="${provider}/dist/index.js"
  local ai_plugin="${provider}/node_modules/@opencode-ai/plugin"
  local clean=1
  if [[ -f "$entry" ]] && grep -q "generated by ocp setup" "$entry" 2>/dev/null; then
    echo "  dist/index.js:              SHIMMED  <- native OpenCode is affected"
    clean=0
  else
    echo "  dist/index.js:              stock"
  fi
  if [[ -L "$ai_plugin" ]]; then
    echo "  node_modules/@opencode-ai:  FACADE SYMLINK  <- native OpenCode is affected"
    clean=0
  else
    echo "  node_modules/@opencode-ai:  real packages"
  fi
  if (( clean )); then
    echo "  => clean; native OpenCode unaffected"
  else
    echo "  => dirty; run: scripts/ocp-dev.sh repair-stock"
  fi
}

# Resolve the host list for a command: explicit names, or every installed host.
resolve_hosts() {
  local -a requested=("$@")
  local host

  if [[ ${#requested[@]} -eq 0 || "${requested[0]}" == "--all" || "${requested[0]}" == "all" ]]; then
    local -a found=()
    while IFS= read -r host; do
      [[ -n "$host" ]] && found+=("$host")
    done < <(ocp_dev_installed_hosts)
    if [[ ${#found[@]} -eq 0 ]]; then
      ocp_dev_die "no supported hosts found on PATH (looked for: $(ocp_dev_known_hosts))"
    fi
    printf '%s\n' "${found[@]}"
    return 0
  fi

  for host in "${requested[@]}"; do
    ocp_dev_host_family "$host" >/dev/null 2>&1 ||
      ocp_dev_die "unknown host: $host (expected $(ocp_dev_known_hosts), or --all)"
    printf '%s\n' "$host"
  done
}

cmd_shim() {
  local mode="local"
  local -a hosts=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mode)
        mode="${2:-}"
        [[ "$mode" == "local" || "$mode" == "npm" ]] || ocp_dev_die "--mode expects local or npm"
        shift 2
        ;;
      --local) mode="local"; shift ;;
      --npm) mode="npm"; shift ;;
      *) hosts+=("$1"); shift ;;
    esac
  done

  local root host script
  root="$(ocp_dev_repo_root)"

  local -a targets=()
  while IFS= read -r host; do
    [[ -n "$host" ]] && targets+=("$host")
  done < <(resolve_hosts "${hosts[@]+"${hosts[@]}"}")

  echo "ocp-dev: shimming ${#targets[@]} host(s) in ${mode} mode: ${targets[*]}"
  echo ""

  local -a ok=() failed=()
  for host in "${targets[@]}"; do
    script="${root}/scripts/${host}-dev.sh"
    if [[ ! -x "$script" ]]; then
      echo "ocp-dev: no dev script for ${host} (${script}) — skipping" >&2
      failed+=("$host")
      continue
    fi
    echo "=== ${host} (${mode}) ==="
    # Keep going on failure: one uninstalled or misconfigured host should not
    # block wiring the rest, and the summary reports exactly what happened.
    if "$script" "$mode"; then ok+=("$host"); else failed+=("$host"); fi
    echo ""
  done

  echo "ocp-dev: shimmed ${#ok[@]} host(s)${ok[0]+: ${ok[*]}}"
  if [[ ${#failed[@]} -gt 0 ]]; then
    echo "ocp-dev: FAILED ${#failed[@]} host(s): ${failed[*]}" >&2
    return 1
  fi
}

# Return every named (or every installed) host to factory state, then restore
# the shared provider checkout if an older script left it dirty.
cmd_unshim() {
  local -a hosts=("$@")
  local root host script family provider

  root="$(ocp_dev_repo_root)"

  local -a targets=()
  while IFS= read -r host; do
    [[ -n "$host" ]] && targets+=("$host")
  done < <(resolve_hosts "${hosts[@]+"${hosts[@]}"}")

  echo "ocp-dev: unshimming ${#targets[@]} host(s): ${targets[*]}"
  echo ""

  for host in "${targets[@]}"; do
    family="$(ocp_dev_host_family "$host")"
    echo "=== ${host} ==="
    case "$family" in
      clone)
        # Manifest-driven: removes exactly the config entry we added and the
        # per-host wrapper, leaving user plugin entries untouched.
        ocp_dev_revert_host "$host"
        ;;
      pi)
        script="${root}/scripts/${host}-dev.sh"
        if [[ -x "$script" ]] && ocp_dev_host_installed "$host"; then
          "$script" unshim || echo "ocp-dev: ${host} unshim reported an error (continuing)" >&2
        else
          echo "ocp-dev: ${host} not installed — nothing to uninstall"
        fi
        # Clone-style state is not used by the pi family, but drop any stale
        # manifest so `status` cannot keep claiming this host is wired.
        ocp_dev_revert_host "$host" >/dev/null 2>&1 || true
        ;;
    esac
    echo ""
  done

  provider="$(ocp_dev_default_provider_path 2>/dev/null || true)"
  if [[ -n "$provider" ]]; then
    local entry="${provider}/dist/index.js"
    local ai_plugin="${provider}/node_modules/@opencode-ai/plugin"
    if { [[ -f "$entry" ]] && grep -q "generated by ocp setup" "$entry" 2>/dev/null; } ||
      [[ -L "$ai_plugin" ]]; then
      echo "ocp-dev: provider checkout is dirty — restoring it as part of unshim"
      ocp_dev_repair_stock "$provider"
    else
      echo "ocp-dev: provider checkout already clean: ${provider}"
    fi
  fi

  echo ""
  echo "ocp-dev: factory state restored"
}

cmd_revert() {
  local target="${1:-}"
  [[ -n "$target" ]] || ocp_dev_die "usage: ocp-dev.sh revert <host>|--all"

  if [[ "$target" == "--all" || "$target" == "all" ]]; then
    local host
    for host in $(ocp_dev_known_hosts); do
      ocp_dev_revert_host "$host"
    done
    return 0
  fi

  case "$target" in
    mimo | kilo | pi | omp) ocp_dev_revert_host "$target" ;;
    *) ocp_dev_die "unknown host: $target (expected mimo|kilo|pi|omp|--all)" ;;
  esac
}

cmd_repair_stock() {
  local provider
  provider="$(ocp_dev_default_provider_path)"
  ocp_dev_repair_stock "$provider"
}

usage() {
  cat <<'EOF'
Usage: ocp-dev.sh <command> [hosts...]

  shim [hosts...]   Wire every installed host (or just the named ones).
                    --mode local (default) or --mode npm.
  unshim [hosts...] Return every installed host (or just the named ones) to
                    factory state, and restore the provider checkout if an
                    older script dirtied it.
  status            Show which hosts are wired, and whether the stock provider
                    checkout is clean (i.e. whether native OpenCode is affected).
  revert <host>     Undo one clone host's config slot and dev state, without
                    touching its host package manager. `unshim` is the fuller
                    reset; this is the narrow one.
  revert --all      Undo every wired clone host.
  repair-stock      Restore a provider checkout that an older in-place host-dev
                    script shimmed or facade-symlinked.

Hosts: mimo, kilo (OpenCode clones) and pi, omp (Pi family). With no host
arguments, shim/unshim act on every host found on PATH.

Examples:
  ocp-dev.sh shim                 # wire everything installed, local mode
  ocp-dev.sh shim --mode npm      # ...against published packages instead
  ocp-dev.sh shim kilo mimo       # only these two
  ocp-dev.sh unshim               # factory state everywhere
  ocp-dev.sh status

Environment:
  OCP_DEV_STATE_DIR      Dev state root (default: ~/.cache/ocp-dev)
  OCP_DEV_PROVIDER_PATH  cursor-opencode-provider checkout
EOF
}

main() {
  local cmd="${1:-}"
  shift || true
  case "$cmd" in
    shim) cmd_shim "$@" ;;
    unshim) cmd_unshim "$@" ;;
    status) cmd_status ;;
    revert) cmd_revert "${1:-}" ;;
    repair-stock) cmd_repair_stock ;;
    -h | --help | help | "") usage ;;
    *) ocp_dev_die "unknown command: $cmd" ;;
  esac
}

main "$@"
