#!/usr/bin/env bash
# Shared state for non-destructive multi-host local dev.
#
# Design invariant: the stock provider checkout is READ-ONLY to OCP tooling.
# Each host gets a private wrapper package under the dev state dir; the host
# config points at that wrapper. Nothing another host (or native OpenCode)
# reads is ever written, so hosts can be wired in any combination.
#
# State layout:
#   ${OCP_DEV_STATE_DIR:-~/.cache/ocp-dev}/<host>/
#     state.json            manifest: mode + exact config slot written
#     provider/             generated wrapper package (dist copy + shim)
set -euo pipefail

ocp_dev_die() {
  echo "ocp-dev: $*" >&2
  exit 1
}

ocp_dev_state_root() {
  echo "${OCP_DEV_STATE_DIR:-${XDG_CACHE_HOME:-${HOME}/.cache}/ocp-dev}"
}

ocp_dev_host_dir() {
  echo "$(ocp_dev_state_root)/$1"
}

ocp_dev_wrapper_dir() {
  echo "$(ocp_dev_host_dir "$1")/provider"
}

ocp_dev_manifest_path() {
  echo "$(ocp_dev_host_dir "$1")/state.json"
}

ocp_dev_known_hosts() {
  echo "mimo kilo pi omp"
}

ocp_dev_require_bun() {
  command -v bun >/dev/null 2>&1 || ocp_dev_die "bun is required"
}

# Resolve a host CLI without dying — used for "which hosts exist here?".
# Mirrors the fallbacks in host-dev-common.sh / pi-family-dev-common.sh.
ocp_dev_host_cli() {
  local host="$1"
  local fallback
  if command -v "$host" >/dev/null 2>&1; then
    command -v "$host"
    return 0
  fi
  case "$host" in
    mimo) fallback="${HOME}/.mimocode/bin/mimo" ;;
    kilo) fallback="${HOME}/.local/bin/kilo" ;;
    pi) fallback="/opt/local/bin/pi" ;;
    omp) fallback="${HOME}/.bun/bin/omp" ;;
    *) return 1 ;;
  esac
  [[ -x "$fallback" ]] || return 1
  echo "$fallback"
}

ocp_dev_host_installed() {
  ocp_dev_host_cli "$1" >/dev/null 2>&1
}

# Every known host that is actually installed on this machine.
ocp_dev_installed_hosts() {
  local host
  for host in $(ocp_dev_known_hosts); do
    if ocp_dev_host_installed "$host"; then echo "$host"; fi
  done
}

ocp_dev_host_family() {
  case "$1" in
    mimo | kilo) echo "clone" ;;
    pi | omp) echo "pi" ;;
    *) return 1 ;;
  esac
}

# Guard against operating on a path that is not ours to delete.
ocp_dev_assert_managed_path() {
  local path="$1"
  local root
  root="$(ocp_dev_state_root)"
  [[ -n "$path" ]] || ocp_dev_die "refusing empty managed path"
  [[ "$path" == "$root"/* ]] || ocp_dev_die "refusing path outside dev state dir: $path"
  [[ "$path" != *".."* ]] || ocp_dev_die "refusing path with traversal: $path"
}

# ---------------------------------------------------------------------------
# Stock checkout protection
# ---------------------------------------------------------------------------

# The whole point of this design: never write to the tree other hosts read.
# Refuse to proceed if a previous generation of these scripts already dirtied
# it, and say exactly how to repair.
ocp_dev_assert_stock_clean() {
  local provider="$1"
  local entry="${provider}/dist/index.js"
  local ai_plugin="${provider}/node_modules/@opencode-ai/plugin"
  local dirty=0

  [[ -d "$provider" ]] || ocp_dev_die "provider checkout not found: $provider"

  if [[ -f "$entry" ]] && grep -q "generated by ocp setup" "$entry" 2>/dev/null; then
    echo "ocp-dev: STOCK DIRTY — ${entry} is an in-place OCP shim" >&2
    dirty=1
  fi
  if [[ -L "$ai_plugin" ]]; then
    echo "ocp-dev: STOCK DIRTY — ${ai_plugin} is a symlink (facades wired into the stock tree)" >&2
    dirty=1
  fi

  if (( dirty )); then
    cat >&2 <<EOF

The stock provider checkout was modified in place by an older host-dev script.
Native OpenCode reads this tree, so it must be restored before wiring any host:

  scripts/ocp-dev.sh repair-stock

EOF
    ocp_dev_die "refusing to wire a host against a dirty stock checkout"
  fi
}

# Restore the stock checkout: real deps + a build from sources. There is no
# backup to restore from by design — reinstall/rebuild is the source of truth.
ocp_dev_repair_stock() {
  local provider="$1"
  [[ -d "$provider" ]] || ocp_dev_die "provider checkout not found: $provider"
  [[ -f "${provider}/package.json" ]] || ocp_dev_die "not a package: $provider"

  echo "ocp-dev: repairing stock checkout ${provider}"
  if [[ -L "${provider}/node_modules/@opencode-ai" ]]; then
    rm -f "${provider}/node_modules/@opencode-ai"
  fi
  local ai_dir="${provider}/node_modules/@opencode-ai"
  if [[ -d "$ai_dir" ]]; then
    local leaf
    for leaf in plugin sdk; do
      if [[ -L "${ai_dir}/${leaf}" ]]; then
        rm -f "${ai_dir}/${leaf}"
        echo "ocp-dev: removed facade symlink ${ai_dir}/${leaf}"
      fi
    done
  fi

  (
    cd "$provider"
    if [[ -f bun.lock ]]; then
      bun install --frozen-lockfile
    elif command -v bun >/dev/null 2>&1; then
      bun install
    else
      npm install
    fi
  ) || ocp_dev_die "dependency restore failed in $provider"

  (
    cd "$provider"
    if command -v bun >/dev/null 2>&1; then bun run build; else npm run build; fi
  ) || ocp_dev_die "stock rebuild failed in $provider"

  local entry="${provider}/dist/index.js"
  [[ -f "$entry" ]] || ocp_dev_die "stock entry missing after rebuild: $entry"
  if grep -q "generated by ocp setup" "$entry" 2>/dev/null; then
    ocp_dev_die "stock entry still shimmed after rebuild: $entry"
  fi
  echo "ocp-dev: stock checkout restored — native OpenCode is unaffected again"
}

# ---------------------------------------------------------------------------
# Wrapper package
# ---------------------------------------------------------------------------

# Populate <wrapper>/node_modules with one symlink per externally-imported
# package, discovered from the built dist rather than hardcoded, so a new
# provider dependency does not silently fail to resolve.
ocp_dev_link_wrapper_deps() {
  local wrapper="$1"
  local stock="$2"
  ocp_dev_require_bun

  bun - "$wrapper" "$stock" <<'BUN'
import { readdirSync, statSync, readFileSync, mkdirSync, symlinkSync, existsSync } from "node:fs"
import { join, dirname } from "node:path"

const [wrapper, stock] = process.argv.slice(2)

const walk = (dir) => {
  const out = []
  for (const name of readdirSync(dir)) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) out.push(...walk(path))
    else if (name.endsWith(".js")) out.push(path)
  }
  return out
}

// Collect bare specifiers, reduced to their package name (scope-aware).
const specifiers = new Set()
for (const file of walk(join(wrapper, "dist"))) {
  const source = readFileSync(file, "utf8")
  for (const match of source.matchAll(/(?:from|import)\s*["']([^"']+)["']/g)) {
    const spec = match[1]
    if (spec.startsWith(".") || spec.startsWith("node:") || spec.startsWith("/")) continue
    const parts = spec.split("/")
    specifiers.add(spec.startsWith("@") ? `${parts[0]}/${parts[1]}` : parts[0])
  }
}

const modules = join(wrapper, "node_modules")
mkdirSync(modules, { recursive: true })

const linked = []
const missing = []
for (const pkg of [...specifiers].sort()) {
  const source = join(stock, "node_modules", pkg)
  if (!existsSync(source)) {
    missing.push(pkg)
    continue
  }
  const target = join(modules, pkg)
  mkdirSync(dirname(target), { recursive: true })
  if (!existsSync(target)) symlinkSync(source, target)
  linked.push(pkg)
}

console.log(`ocp-dev: linked ${linked.length} wrapper dep(s): ${linked.join(", ")}`)
if (missing.length > 0) {
  console.error(
    `ocp-dev: ${missing.length} imported package(s) missing from the stock tree: ${missing.join(", ")}\n` +
      `  run: (cd ${stock} && bun install)`,
  )
  process.exit(1)
}
BUN
}

# Build a private, per-host copy of the provider and instrument THAT copy with
# the same shim machinery `ocp setup` uses. `dist/` is ~1MB so copying is cheap;
# `node_modules` is symlinked to the stock tree so the provider's one runtime
# import (`tool` from @opencode-ai/plugin) resolves to the real package.
ocp_dev_build_wrapper() {
  local host="$1"
  local stock="$2"
  local ocp_root="$3"
  local wrapper
  wrapper="$(ocp_dev_wrapper_dir "$host")"
  ocp_dev_assert_managed_path "$wrapper"
  ocp_dev_require_bun

  [[ -d "${stock}/dist" ]] || ocp_dev_die "stock dist missing: ${stock}/dist (run bun run build in the provider checkout)"
  [[ -f "${stock}/package.json" ]] || ocp_dev_die "stock package.json missing: ${stock}"

  # Always regenerate: the OCP adapter runtime or version may have moved since
  # this wrapper was last written.
  rm -rf "$wrapper"
  mkdir -p "$wrapper"

  cp "${stock}/package.json" "${wrapper}/package.json"
  cp -R "${stock}/dist" "${wrapper}/dist"

  # node_modules is a REAL directory holding one symlink per package the built
  # dist actually imports — never a symlink to the stock node_modules. That
  # distinction matters: `ocp setup --absolute-plugins` rewrites
  # `@opencode-ai/*` inside a configured plugin's tree, and if this were a
  # symlink to the stock tree that rewrite would land on the checkout native
  # OpenCode reads. Per-package symlinks keep writes inside the wrapper while
  # transitive deps still resolve, because Node continues resolution from each
  # symlink's realpath in the stock tree.
  ocp_dev_link_wrapper_deps "$wrapper" "$stock"

  # Instrument the copy, not the stock tree.
  bun - "$wrapper" "$host" "$ocp_root" <<'BUN'
const [wrapperDir, host, ocpRoot] = process.argv.slice(2)
// provider-shim ships as its own dist module; import it directly rather than
// widening the CLI package's public export surface for a dev script.
const { setupProviderShims } = await import(`${ocpRoot}/packages/cli/dist/provider-shim.js`)
const result = setupProviderShims({ dir: wrapperDir, rootOnly: true, hostHint: host })
console.log(result.message)
if (!result.ok) process.exit(1)
const changed = result.targets.filter((t) => t.changed).length
if (changed === 0) {
  console.error("ocp-dev: wrapper was not instrumented; refusing to wire a stock passthrough")
  process.exit(1)
}
BUN

  local entry="${wrapper}/dist/index.js"
  [[ -f "$entry" ]] || ocp_dev_die "wrapper entry missing: $entry"
  grep -q "generated by ocp setup" "$entry" || ocp_dev_die "wrapper entry is not instrumented: $entry"
  [[ -f "${wrapper}/dist/ocp-lm-runtime.js" ]] || ocp_dev_die "wrapper runtime missing beside entry"

  echo "ocp-dev: wrapper ready for ${host} → ${entry}"
}

# ---------------------------------------------------------------------------
# Config slot + manifest
# ---------------------------------------------------------------------------

# Apply this host's OCP slot to its config, evicting whatever the previous run
# recorded. User-authored plugin entries are preserved; only the recorded slot
# is replaced. Writes the manifest as the same operation so the two cannot
# drift apart.
ocp_dev_apply_slot() {
  local host="$1"
  local config_file="$2"
  local mode="$3"
  local plugin_entry="$4"
  local provider_npm="$5"
  local stock="$6"
  local wrapper="$7"
  local manifest
  manifest="$(ocp_dev_manifest_path "$host")"
  mkdir -p "$(dirname "$manifest")"
  ocp_dev_require_bun

  bun - "$config_file" "$manifest" "$host" "$mode" "$plugin_entry" "$provider_npm" "$stock" "$wrapper" <<'BUN'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs"
import { dirname, resolve as pathResolve } from "node:path"

const [configPath, manifestPath, host, mode, pluginEntry, providerNpm, stock, wrapper] =
  process.argv.slice(2)

const stripComments = (s) =>
  s.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/.*$/gm, "$1")

const readJson = (path, fallback) => {
  try {
    return JSON.parse(stripComments(readFileSync(path, "utf8")))
  } catch {
    return fallback
  }
}

let raw = "{}"
try {
  raw = readFileSync(configPath, "utf8")
} catch {
  mkdirSync(dirname(configPath), { recursive: true })
}

const data = JSON.parse(stripComments(raw))
const prior = existsSync(manifestPath) ? readJson(manifestPath, null) : null

// Absolute / file:// entries that resolve inside the stock provider checkout.
// Leaving those in plugin[] makes `ocp setup --absolute-plugins` instrument the
// shared tree native OpenCode reads — exactly the dirty-stock failure mode.
const stockRoot = pathResolve(stock)
const isStockPluginEntry = (entry) => {
  if (typeof entry !== "string" || !entry) return false
  let path = entry
  if (path.startsWith("file://")) {
    try {
      path = decodeURIComponent(new URL(path).pathname)
    } catch {
      return false
    }
  }
  if (!path.startsWith("/")) return false
  const resolved = pathResolve(path)
  return resolved === stockRoot || resolved.startsWith(stockRoot + "/")
}

// --- evict the previous OCP slot + any stock checkout paths -----------------
const priorEntry = prior?.config?.pluginAdded
const before = Array.isArray(data.plugin) ? data.plugin : data.plugin ? [data.plugin] : []
const stockEvictedNow = before.filter(
  (entry) =>
    isStockPluginEntry(entry) &&
    entry !== priorEntry &&
    entry !== pluginEntry,
)
// Preserve stock entries the user had before our first wire so revert can put
// them back. Later re-shims keep the first-captured list.
const stockPluginEntriesBefore = prior?.config?.stockPluginEntriesBefore ?? stockEvictedNow
let plugins = before.filter(
  (entry) => entry !== priorEntry && entry !== pluginEntry && !isStockPluginEntry(entry),
)
const evicted = before.length - plugins.length

// provider.cursor is likewise a single slot: capture what was there the FIRST
// time we touched it, so revert restores the user's original rather than a
// value we ourselves wrote on an earlier run.
const hadPriorManifest = prior !== null
const providerCursorBefore = hadPriorManifest
  ? (prior.config?.providerCursorBefore ?? null)
  : (data.provider?.cursor ?? null)

// --- write the new slot -----------------------------------------------------
plugins.push(pluginEntry)
data.plugin = plugins

if (providerNpm) {
  data.provider = data.provider ?? {}
  const existingModels = data.provider.cursor?.models ?? providerCursorBefore?.models ?? {}
  data.provider.cursor = {
    ...(providerCursorBefore && typeof providerCursorBefore === "object" ? providerCursorBefore : {}),
    npm: providerNpm,
    name: data.provider.cursor?.name ?? providerCursorBefore?.name ?? "Cursor",
    models: existingModels,
  }
}

writeFileSync(configPath, `${JSON.stringify(data, null, 2)}\n`, "utf8")

const manifest = {
  host,
  mode,
  ocpVersion: readJson(`${process.cwd()}/packages/profile/package.json`, {}).version ?? null,
  updated: new Date().toISOString(),
  stockProvider: stock,
  wrapperDir: wrapper || null,
  config: {
    path: configPath,
    pluginAdded: pluginEntry,
    providerCursorBefore,
    stockPluginEntriesBefore,
  },
}
mkdirSync(dirname(manifestPath), { recursive: true })
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8")

const stockNote =
  stockEvictedNow.length > 0
    ? ` (removed ${stockEvictedNow.length} stock checkout plugin path(s))`
    : ""
console.log(
  `ocp-dev: ${host} slot → ${configPath}` +
    (evicted > 0 ? ` (evicted ${evicted} prior OCP entry/entries)` : "") +
    stockNote +
    ` — ${plugins.length - 1} user plugin entry/entries preserved`,
)
BUN
}

# Remove this host's OCP slot from its config and delete its state, using the
# manifest so we touch exactly what we wrote and nothing else.
ocp_dev_revert_host() {
  local host="$1"
  local manifest host_dir
  manifest="$(ocp_dev_manifest_path "$host")"
  host_dir="$(ocp_dev_host_dir "$host")"

  if [[ ! -f "$manifest" ]]; then
    echo "ocp-dev: ${host} is not wired (no manifest)"
    return 0
  fi
  ocp_dev_require_bun

  bun - "$manifest" <<'BUN'
import { readFileSync, writeFileSync, existsSync } from "node:fs"

const [manifestPath] = process.argv.slice(2)
const stripComments = (s) =>
  s.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|\s)\/\/.*$/gm, "$1")
const manifest = JSON.parse(readFileSync(manifestPath, "utf8"))
const configPath = manifest.config?.path
if (!configPath || !existsSync(configPath)) {
  console.log(`ocp-dev: config already absent (${configPath ?? "unknown"})`)
  process.exit(0)
}

const data = JSON.parse(stripComments(readFileSync(configPath, "utf8")))
const added = manifest.config?.pluginAdded
const stockRestore = Array.isArray(manifest.config?.stockPluginEntriesBefore)
  ? manifest.config.stockPluginEntriesBefore.filter((entry) => typeof entry === "string" && entry)
  : []
const before = Array.isArray(data.plugin) ? data.plugin : []
let after = before.filter((entry) => entry !== added)
// Put back absolute stock-checkout paths we removed on wire, without duplicating.
for (const entry of stockRestore) {
  if (!after.includes(entry)) after.push(entry)
}
if (after.length > 0) data.plugin = after
else delete data.plugin

const restore = manifest.config?.providerCursorBefore ?? null
if (restore && typeof restore === "object") {
  data.provider = data.provider ?? {}
  data.provider.cursor = restore
} else if (data.provider?.cursor) {
  delete data.provider.cursor
  if (Object.keys(data.provider).length === 0) delete data.provider
}

writeFileSync(configPath, `${JSON.stringify(data, null, 2)}\n`, "utf8")
const restoredCount = stockRestore.filter((e) => after.includes(e) && !before.includes(e)).length
console.log(
  `ocp-dev: reverted ${manifest.host} slot in ${configPath}` +
    ` (removed OCP entry, restored ${restoredCount} stock path(s), ${after.length} plugin entr${after.length === 1 ? "y" : "ies"} remain)`,
)
BUN

  ocp_dev_assert_managed_path "$host_dir"
  rm -rf "$host_dir"
  echo "ocp-dev: removed dev state ${host_dir}"
}
