#!/usr/bin/env bun
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { pathToFileURL } from "node:url"

const runtimePath = join(import.meta.dir, "..", "dist", "ocp-lm-runtime.js")
const source = readFileSync(runtimePath, "utf8")

if (!source.includes("generated by ocp setup")) {
  throw new Error("ocp-lm-runtime.js is missing the setup marker")
}

if (source.includes("@opencode-compat/")) {
  throw new Error("ocp-lm-runtime.js must not contain live @opencode-compat imports")
}

const runtime = await import(pathToFileURL(runtimePath).href) as Record<string, unknown>

for (const name of [
  "detectHostId",
  "installPathBridge",
  "policyForHostId",
  "toolRolesForHostId",
  "wrapProviderModule",
]) {
  if (typeof runtime[name] !== "function") {
    throw new Error(`ocp-lm-runtime.js is missing function export ${name}`)
  }
}
