import { mkdir } from "node:fs/promises"
import { join } from "node:path"
import type {
  EmittedTreeManifest,
  FoundManifest,
  PluginScan,
} from "./types"

function pickString(
  raw: Record<string, unknown>,
  key: string,
): string | undefined {
  const v = raw[key]
  return typeof v === "string" && v.trim() ? v.trim() : undefined
}

/** Build `.zcode-plugin/plugin.json` from scan + optional source manifests. */
export function buildPluginJson(
  scan: PluginScan,
  options: { name?: string; version?: string },
): Record<string, unknown> {
  const zcode = scan.manifests.find((m) => m.kind === "zcode-plugin")
  const claude = scan.manifests.find((m) => m.kind === "claude-plugin")
  const codex = scan.manifests.find((m) => m.kind === "codex-plugin")
  const source = zcode?.raw ?? claude?.raw ?? codex?.raw ?? {}

  const name =
    options.name ??
    pickString(source, "name") ??
    scan.packageName ??
    "migrated-plugin"

  const version =
    options.version ??
    pickString(source, "version") ??
    scan.packageVersion ??
    "0.0.0"

  const description =
    pickString(source, "description") ??
    `Migrated by @opencode-compat/migrate-zcode — marketplace assets only; not an OpenCode npm plugin ABI package.`

  const pluginJson: Record<string, unknown> = {
    name,
    version,
    description,
  }

  if (scan.skills.length > 0) pluginJson.skills = "./skills"
  if (scan.commands.length > 0) pluginJson.commands = "./commands"

  // Carry non-MCP path hints from an existing zcode manifest when present.
  if (zcode) {
    for (const key of ["agents", "hooks", "lsp"] as const) {
      if (key in zcode.raw) pluginJson[key] = zcode.raw[key]
    }
  }

  return pluginJson
}

export async function emitPluginTree(
  scan: PluginScan,
  outDir: string,
  options: {
    name?: string
    version?: string
    /** When wrapping into a parent marketplace, do not nest marketplace.json. */
    skipMarketplaceCopy?: boolean
  },
): Promise<EmittedTreeManifest> {
  await mkdir(join(outDir, ".zcode-plugin"), { recursive: true })
  const pluginJson = buildPluginJson(scan, options)
  await Bun.write(
    join(outDir, ".zcode-plugin", "plugin.json"),
    `${JSON.stringify(pluginJson, null, 2)}\n`,
  )

  const skills: string[] = []
  for (const skill of scan.skills) {
    const dest = join(outDir, skill.relPath)
    await mkdir(join(dest, ".."), { recursive: true })
    await Bun.write(dest, skill.body.endsWith("\n") ? skill.body : `${skill.body}\n`)
    skills.push(skill.relPath)
  }

  const commands: string[] = []
  for (const command of scan.commands) {
    const rel = `commands/${command.fileName}`
    const dest = join(outDir, rel)
    await mkdir(join(outDir, "commands"), { recursive: true })
    await Bun.write(
      dest,
      command.body.endsWith("\n") ? command.body : `${command.body}\n`,
    )
    commands.push(rel)
  }

  const copiedManifests: string[] = []
  if (!options.skipMarketplaceCopy) {
    const marketplaces = scan.manifests.filter(
      (m): m is FoundManifest => m.kind === "marketplace",
    )
    for (const m of marketplaces) {
      // Prefer canonical location under .zcode-plugin/
      const dest = join(outDir, ".zcode-plugin", "marketplace.json")
      await Bun.write(dest, `${JSON.stringify(m.raw, null, 2)}\n`)
      copiedManifests.push(".zcode-plugin/marketplace.json")
      break
    }
  }

  const readme = [
    `# ${String(pluginJson.name)}`,
    "",
    "Generated by `@opencode-compat/migrate-zcode`.",
    "",
    "This package contains **marketplace assets** (skills / commands / manifests) for ZCode.",
    "It does **not** run OpenCode `@opencode-ai/plugin` JavaScript hooks.",
    "",
    `Source: \`${scan.pluginDir}\``,
    "",
  ].join("\n")
  await Bun.write(join(outDir, "README.md"), readme)

  return { pluginJson, skills, commands, copiedManifests }
}