import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"
import { homedir } from "node:os"
import { configDir, type HostId, type WireMode } from "./hosts.ts"
import { defaultProviderPath, pluginName, repoRoot } from "./paths.ts"
import { hostStateDir, writeAtomic } from "./paths.ts"

export type DshHost = Extract<HostId, "dsh">

function run(cwd: string | undefined, cmd: string[]): void {
  const result = Bun.spawnSync({ cmd, cwd, stdout: "inherit", stderr: "inherit" })
  if (result.exitCode !== 0) throw new Error(`${cmd.join(" ")} failed`)
}

function dshBridgePath(): string {
  return join(repoRoot(), "packages/dsh-bridge")
}

function harnessRoot(): string | undefined {
  const candidates = [
    process.env.DSH_HARNESS_ROOT,
    join(homedir(), "Projects", "deepseek-harness"),
    join(repoRoot(), "..", "deepseek-harness"),
  ].filter(Boolean) as string[]
  for (const c of candidates) if (existsSync(join(c, "package.json")) && existsSync(join(c, "packages", "bundle"))) return c
  return undefined
}

function buildLocal(provider: string): void {
  const root = repoRoot()
  const bridge = dshBridgePath()
  const loader = join(root, "packages/opencode-loader")
  console.log("ocp-dev: installing locked OCP workspace dependencies")
  run(root, ["bun", "install", "--frozen-lockfile"])
  console.log("ocp-dev: building local opencode-loader")
  run(loader, ["bun", "run", "build"])
  console.log("ocp-dev: building local dsh-bridge")
  run(bridge, ["bun", "run", "build"])
  for (const entry of ["index.js"]) {
    if (!existsSync(join(bridge, "dist", entry))) throw new Error(`dsh-bridge entry missing after build: ${entry}`)
  }
  console.log("ocp-dev: installing local provider dependencies")
  if (existsSync(join(provider, "bun.lock"))) run(provider, ["bun", "install", "--frozen-lockfile"])
  else if (existsSync(join(provider, "package-lock.json"))) run(provider, ["npm", "ci"])
  else run(provider, ["bun", "install"])
  console.log("ocp-dev: building local provider")
  run(provider, ["bun", "run", "build"])
  if (!existsSync(join(provider, "dist", "index.js"))) throw new Error("provider entry missing after build")
}

function devPatchPath(): string {
  return join(hostStateDir("dsh"), "patch.yml")
}

function writeDevPatch(provider: string, plugin: string): string {
  const providerDist = resolve(join(provider, "dist", "index.js"))
  // For --patch overlay, use the bundle name (installed via `dsh plugin add` below).
  // Absolute dist paths as `name` break client module composition.
  const yaml = `# Generated by ocp-dev.sh run dsh (local) — do not edit manually
# Persistent profile already has the bridge bundle; this overlay is only for
# ad-hoc ` + "`pnpm dsh web --patch " + devPatchPath() + "`" + ` testing.
# The web profile's own cordis.patch.yml is the primary dev surface.
- id: ocp-dsh-bridge
  config:
    providers:
      - package: '${providerDist}'
        apiKey: CURSOR_API_KEY
`
  const out = devPatchPath()
  mkdirSync(join(out, ".."), { recursive: true })
  writeAtomic(out, yaml)
  return out
}

function persistentPatchPath(): string {
  // User's persistent profile patch (applied after bundles) — for `dsh plugin` style
  const dshHome = process.env.DSH_HOME ?? join(homedir(), ".dsh")
  return join(dshHome, "profiles", "web", "cordis.patch.yml")
}

export async function runDsh(host: DshHost, mode: WireMode): Promise<void> {
  const provider = defaultProviderPath()
  const plugin = pluginName()
  const harness = harnessRoot()

  if (mode === "local") {
    buildLocal(provider)
    // Persistent install via `dsh plugin add file:` — the profile's bundle name is `@opencode-compat/dsh-bridge`
    // (its cordis.patch.yml inserts the bridge row). This avoids absolute `name:` in --patch which breaks client modules.
    const dshBin = Bun.which("dsh") ?? (harness ? join(harness, "node_modules/.bin/dsh") : undefined)
    const pluginAdd = (pkg: string) => {
      // Prefer `pnpm dsh plugin` from harness repo (works without global dsh)
      if (harness) {
        try { run(harness, ["pnpm", "dsh", "plugin", "--profile", "web", "add", `file:${pkg}`]); return } catch {}
      }
      if (dshBin) run(undefined, [dshBin, "plugin", "--profile", "web", "add", `file:${pkg}`])
      else throw new Error("dsh CLI not found and no harness repo")
    }
    try {
      // opencode-loader as plain dep (no bundle) must be first so dsh-bridge's file dep resolves
      const loaderPath = join(repoRoot(), "packages/opencode-loader")
      try { pluginAdd(loaderPath) } catch (e) { console.log(`ocp-dev: opencode-loader add note: ${e instanceof Error ? e.message : e}`) }
      pluginAdd(dshBridgePath())
    } catch (e) {
      console.log(`ocp-dev: dsh plugin add failed (${e instanceof Error ? e.message : e}) — falling back to --patch overlay`)
    }
    // Write persistent profile patch (primary) and ad-hoc --patch overlay
    const providerDist = resolve(join(provider, "dist", "index.js"))
    const persistent = persistentPatchPath()
    const persistentYaml = `- id: ocp-dsh-bridge\n  config:\n    providers:\n      - package: '${providerDist}'\n        apiKey: CURSOR_API_KEY\n`
    mkdirSync(join(persistent, ".."), { recursive: true })
    writeAtomic(persistent, persistentYaml)
    const patch = writeDevPatch(provider, plugin)
    console.log(`\nocp-dev: dsh is on LOCAL dsh-bridge + LOCAL ${plugin}`)
    console.log(`  bridge: ${dshBridgePath()}/dist/index.js`)
    console.log(`  provider: ${providerDist}`)
    console.log(`  persistent patch: ${persistent}`)
    console.log(`  dev overlay: ${patch} (for ad-hoc pnpm dsh web --patch)`)
    console.log(`\n  Verify:`)
    console.log(`    pnpm --prefix ${harness ?? "~/Projects/deepseek-harness"} dsh --profile web --dump-config | grep -A3 ocp-dsh`)
    console.log(`  Run:`)
    console.log(`    pnpm --prefix ${harness ?? "~/Projects/deepseek-harness"} dsh web`)
    if (harness) console.log(`    # (no --patch needed — profile already has the bridge)`)
    return
  }

  // npm mode — published packages
  const bridgeVersion = process.env.OCP_DEV_BRIDGE_VERSION || "latest"
  const pluginVersion = process.env.OCP_DEV_PLUGIN_VERSION || "latest"
  console.log(`ocp-dev: dsh npm mode would run:`)
  console.log(`  dsh plugin --profile web add @opencode-compat/dsh-bridge@${bridgeVersion}`)
  console.log(`  dsh plugin --profile web add ${plugin}@${pluginVersion}`)
  console.log(`  (then ensure cordis.patch.yml has providers: [{package: "${plugin}"}])`)
  // Try to run if dsh is on PATH
  const dshBin = Bun.which("dsh")
  if (dshBin) {
    console.log(`\n  Attempting npm installs via ${dshBin}...`)
    const harness = harnessRoot()
    const cwd = harness ?? undefined
    // Use dsh plugin add which forwards to pnpm in profile dir; fall back to pnpm dsh if needed
    try {
      run(cwd, [dshBin, "plugin", "--profile", "web", "add", `@opencode-compat/dsh-bridge@${bridgeVersion}`])
      run(cwd, [dshBin, "plugin", "--profile", "web", "add", `${plugin}@${pluginVersion}`])
      console.log(`\nocp-dev: dsh is on NPM dsh-bridge@${bridgeVersion} + NPM ${plugin}@${pluginVersion}`)
    } catch {
      console.log(`ocp-dev: dsh plugin add failed — edit ${persistentPatchPath()} manually`)
    }
  } else {
    console.log(`\n  dsh not on PATH — run from harness repo:`)
    console.log(`    pnpm dsh plugin --profile web add @opencode-compat/dsh-bridge@${bridgeVersion}`)
  }
}

export async function unshimDsh(host: DshHost): Promise<void> {
  const patch = devPatchPath()
  try {
    const { rmSync } = await import("node:fs")
    rmSync(patch, { force: true })
    console.log(`ocp-dev: removed dev patch ${patch}`)
  } catch {}
  // Also try to remove persistent plugin if present
  const dshBin = Bun.which("dsh")
  const harness = harnessRoot()
  const cwd = harness ?? undefined
  const plugin = pluginName()
  if (dshBin) {
    try { run(cwd, [dshBin, "plugin", "--profile", "web", "remove", "@opencode-compat/dsh-bridge"]) } catch {}
    try { run(cwd, [dshBin, "plugin", "--profile", "web", "remove", plugin]) } catch {}
  }
  console.log(`ocp-dev: dsh returned to factory state (dev patch removed)`)
  console.log(`  If you used persistent install, also check ${persistentPatchPath()}`)
}
