import { existsSync, lstatSync, readFileSync, rmSync, unlinkSync } from "node:fs"
import { join } from "node:path"


function run(cwd: string, cmd: string[]): void {
  const result = spawnSyncSafe(cwd, cmd)
  if (result.exitCode !== 0) {
    throw new Error(`${cmd.join(" ")} failed in ${cwd}`)
  }
}

function spawnSyncSafe(cwd: string, cmd: string[]) {
  return Bun.spawnSync({
    cmd,
    cwd,
    stdout: "inherit",
    stderr: "inherit",
  })
}

export function assertSafeProvider(provider: string): void {
  if (!provider || provider === "/" || provider === process.env.HOME) {
    throw new Error(`refusing unsafe provider checkout path: ${provider || "<empty>"}`)
  }
  if (!existsSync(join(provider, "package.json"))) {
    throw new Error(`provider package.json missing: ${provider}`)
  }
}

export function isStockDirty(provider: string): boolean {
  const entry = join(provider, "dist", "index.js")
  const aiPlugin = join(provider, "node_modules", "@opencode-ai", "plugin")
  if (existsSync(entry) && readFileSync(entry, "utf8").includes("generated by ocp setup")) return true
  try {
    return lstatSync(aiPlugin).isSymbolicLink()
  } catch {
    return false
  }
}

export function assertStockClean(provider: string): void {
  if (!existsSync(provider)) throw new Error(`provider checkout not found: ${provider}`)
  if (!isStockDirty(provider)) return
  throw new Error(
    `stock provider checkout is dirty (in-place shim or facade symlink).\n  run: scripts/ocp-dev.sh unshim`,
  )
}

export function ensureStockBuild(provider: string): void {
  const entry = join(provider, "dist", "index.js")
  if (existsSync(entry)) return
  console.log(`ocp-dev: stock dist missing — building once in ${provider}`)
  run(provider, existsSync(join(provider, "bun.lock")) ? ["bun", "run", "build"] : ["npm", "run", "build"])
  if (!existsSync(entry)) throw new Error(`provider entry missing after build: ${entry}`)
}

export function repairStock(provider: string): void {
  assertSafeProvider(provider)
  console.log(`ocp-dev: repairing stock checkout ${provider}`)
  const ai = join(provider, "node_modules", "@opencode-ai")
  try {
    if (lstatSync(ai).isSymbolicLink()) unlinkSync(ai)
  } catch {
    // absent
  }
  for (const leaf of ["plugin", "sdk"]) {
    const path = join(ai, leaf)
    try {
      if (lstatSync(path).isSymbolicLink()) {
        unlinkSync(path)
        console.log(`ocp-dev: removed facade symlink ${path}`)
      }
    } catch {
      // absent
    }
  }
  if (existsSync(join(provider, "bun.lock"))) run(provider, ["bun", "install", "--frozen-lockfile"])
  else if (existsSync(join(provider, "package-lock.json"))) run(provider, ["npm", "ci"])
  else run(provider, ["bun", "install"])
  run(provider, ["bun", "run", "build"])
  const entry = join(provider, "dist", "index.js")
  if (!existsSync(entry)) throw new Error(`stock entry missing after rebuild: ${entry}`)
  if (readFileSync(entry, "utf8").includes("generated by ocp setup")) {
    throw new Error(`stock entry still shimmed after rebuild: ${entry}`)
  }
  for (const name of ["index.ocp-original.js", "ocp-lm-runtime.js", "ocp-shim-meta.json"]) {
    const artifact = join(provider, "dist", name)
    if (existsSync(artifact)) rmSync(artifact)
  }
  console.log("ocp-dev: stock checkout restored")
}
