import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, symlinkSync } from "node:fs"
import { cpSync } from "node:fs"
import { dirname, join } from "node:path"
import { assertManaged, repoRoot, wrapperDir } from "./paths.ts"

function walkJs(dir: string): string[] {
  const out: string[] = []
  for (const name of readdirSync(dir)) {
    const path = join(dir, name)
    if (statSync(path).isDirectory()) out.push(...walkJs(path))
    else if (name.endsWith(".js")) out.push(path)
  }
  return out
}

function packageName(spec: string): string {
  const parts = spec.split("/")
  return spec.startsWith("@") ? `${parts[0]}/${parts[1]}` : parts[0]!
}

export function linkWrapperDeps(wrapper: string, stock: string): void {
  const specifiers = new Set<string>()
  for (const file of walkJs(join(wrapper, "dist"))) {
    const source = readFileSync(file, "utf8")
    const from = source.matchAll(/\b(?:from|import)\s+["']([^"']+)["']/g)
    for (const match of from) {
      const spec = match[1]!
      if (!spec || spec.startsWith(".") || spec.startsWith("node:") || spec.startsWith("/")) continue
      specifiers.add(packageName(spec))
    }
  }
  const modules = join(wrapper, "node_modules")
  mkdirSync(modules, { recursive: true })
  const linked: string[] = []
  const missing: string[] = []
  for (const pkg of [...specifiers].sort()) {
    const source = join(stock, "node_modules", pkg)
    if (!existsSync(source)) {
      missing.push(pkg)
      continue
    }
    const target = join(modules, pkg)
    mkdirSync(dirname(target), { recursive: true })
    if (!existsSync(target)) symlinkSync(source, target)
    linked.push(pkg)
  }
  console.log(`ocp-dev: linked ${linked.length} wrapper dep(s): ${linked.join(", ")}`)
  if (missing.length > 0) {
    throw new Error(
      `${missing.length} imported package(s) missing from the stock tree: ${missing.join(", ")}\n  run: (cd ${stock} && bun install)`,
    )
  }
}

export async function buildWrapper(host: string, stock: string): Promise<string> {
  const wrapper = wrapperDir(host)
  assertManaged(wrapper)
  if (!existsSync(join(stock, "dist"))) {
    throw new Error(`stock dist missing: ${join(stock, "dist")} (run bun run build in the provider checkout)`)
  }
  rmSync(wrapper, { recursive: true, force: true })
  mkdirSync(wrapper, { recursive: true })
  cpSync(join(stock, "package.json"), join(wrapper, "package.json"))
  cpSync(join(stock, "dist"), join(wrapper, "dist"), { recursive: true })
  linkWrapperDeps(wrapper, stock)

  const root = repoRoot()
  const src = join(root, "packages/cli/src/provider-shim.ts")
  const dist = join(root, "packages/cli/dist/provider-shim.js")
  const url = existsSync(src) ? src : dist
  const { setupProviderShims } = await import(url)
  const result = setupProviderShims({ dir: wrapper, rootOnly: true, hostHint: host }) as {
    ok: boolean
    message: string
    targets: Array<{ changed: boolean }>
  }
  console.log(result.message)
  if (!result.ok) throw new Error("wrapper instrumentation failed")
  if (!result.targets.some((target) => target.changed)) {
    throw new Error("wrapper was not instrumented; refusing to wire a stock passthrough")
  }
  const entry = join(wrapper, "dist", "index.js")
  if (!existsSync(entry)) throw new Error(`wrapper entry missing: ${entry}`)
  if (!readFileSync(entry, "utf8").includes("generated by ocp setup")) {
    throw new Error(`wrapper entry is not instrumented: ${entry}`)
  }
  if (!existsSync(join(wrapper, "dist", "ocp-lm-runtime.js"))) {
    throw new Error("wrapper runtime missing beside entry")
  }
  console.log(`ocp-dev: wrapper ready for ${host} → ${entry}`)
  return entry
}
